server:
  port: ${APP_SERVER_PORT:8080}
  shutdown: graceful

spring:
  data:
    mongodb:
      auto-index-creation: true
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN
  zipkin:
    enabled: false
  sleuth:
    baggage:
      remote-fields: X-Client-Ip
      correlation-fields: X-Client-Ip

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.selfcare: ${APP_LOG_LEVEL:DEBUG}
  pattern:
    additional-info: ",%X{X-Client-Ip:-}]"

app:
  pageSize: ${PAGE_SIZE:250}
  local:
    csv: ${LOCAL_CSV:true}
    ec: csv/EC-Data-12.csv
    pt: csv/PT-Data.csv
    ecptrelationship: csv/Delegations-Data-4.csv
    user: csv/User-Troppi-Duplicati.csv
